name: Laravel Tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      # 🔥 This is what you're asking for:
      - name: Create SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Set SQLite DB path in .env
        run: echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

      # Optional: See Laravel logs on failure
      - name: View Laravel log on failure
        if: failure()
        run: cat storage/logs/laravel.log || echo "No log file"

